name: clima
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cartopy
  - gdal
  - plotly=4.14.3
  - ipywidgets
  - scikit-learn
  - jupyterlab
  - notebook
  - pip
  - pip:
      - wradlib
